//
//  CommanParameter.h
//  AoSmart
//
//  Created by rakwireless on 16/1/21.
//  Copyright © 2016年 rak. All rights reserved.
//

#ifndef CommanParameter_h
#define CommanParameter_h

#define diff_top  20
#define diff_bottom  20
#define diff_x  10
#define title_size  36
#define main_help_size  22
#define add_title_size  22
#define add_text_size  18
#define add_bg  242
#define diff_help_x 5
#define list_row_height 50
#define list_group_height 44

#define STREAM_URL_KEY @"STREAM_URL_KEY"
#define PAUSE_SCREEN_PHOTO_ENABLE_KEY @"PAUSE_SCREEN_PHOTO_ENABLE_KEY"
#define PAUSE_SCREEN_PHOTO_SRC_KEY @"PAUSE_SCREEN_PHOTO_SRC_KEY"
#define PAUSE_SCREEN_VIDEO_ENABLE_KEY @"PAUSE_SCREEN_VIDEO_ENABLE_KEY"
#define PAUSE_SCREEN_VIDEO_SRC_KEY @"PAUSE_SCREEN_VIDEO_SRC_KEY"
#define BANNER_PHOTO_ENABLE_KEY @"BANNER_PHOTO_ENABLE_KEY"
#define BANNER_UPPER_LEFT_KEY @"BANNER_UPPER_LEFT_KEY"
#define BANNER_UPPER_RIGHT_KEY @"BANNER_UPPER_RIGHT_KEY"
#define BANNER_LOWER_LEFT_KEY @"BANNER_LOWER_LEFT_KEY"
#define BANNER_LOWER_RIGHT_KEY @"BANNER_LOWER_RIGHT_KEY"
#define BANNER_UPPER_LEFT_PUSH_KEY @"BANNER_UPPER_LEFT_PUSH_KEY"
#define BANNER_UPPER_RIGHT_PUSH_KEY @"BANNER_UPPER_RIGHT_PUSH_KEY"
#define BANNER_LOWER_LEFT_PUSH_KEY @"BANNER_LOWER_LEFT_PUSH_KEY"
#define BANNER_LOWER_RIGHT_PUSH_KEY @"BANNER_LOWER_RIGHT_PUSH_KEY"
#define BANNER_DURATION_KEY @"BANNER_DURATION_KEY"
#define BANNER_INTERVAL_KEY @"BANNER_INTERVAL_KEY"
#define BANNER_OPACITY_KEY @"BANNER_OPACITY_KEY"
#define SUBTITLE_ENABLE_KEY @"SUBTITLE_ENABLE_KEY"
#define SUBTITLE_PHOTO_KEY @"SUBTITLE_PHOTO_KEY"
#define SUBTITLE_PHOTO_PUSH_KEY @"SUBTITLE_PHOTO_PUSH_KEY"
#define SUBTITLE_DURATION_KEY @"SUBTITLE_DURATION_KEY"
#define SUBTITLE_INTERVAL_KEY @"SUBTITLE_INTERVAL_KEY"
#define SUBTITLE_OPACITY_KEY @"SUBTITLE_OPACITY_KEY"
#define SUBTITLE_COLOR_KEY @"SUBTITLE_COLOR_KEY"
#define SUBTITLE_SIZE_KEY @"SUBTITLE_SIZE_KEY"
#define SUBTITLE_TEXT_KEY @"SUBTITLE_TEXT_KEY"
#define SUBTITLE_SHOW_TYPE_KEY @"SUBTITLE_SHOW_TYPE_KEY"
#endif /* CommanParameter_h */
